# Generated by Django 5.2.1 on 2025-05-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FbsStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField()),
                ('sku', models.BigIntegerField()),
                ('fbs_sku', models.BigIntegerField()),
                ('present', models.PositiveIntegerField(default=0)),
                ('reserved', models.PositiveIntegerField(default=0)),
                ('warehouse_id', models.BigIntegerField()),
                ('warehouse_name', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FBS остаток',
                'verbose_name_plural': 'FBS остатки',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField(unique=True)),
                ('sku', models.BigIntegerField(unique=True)),
                ('offer_id', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('barcodes', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('type_name', models.CharField(blank=True, max_length=255)),
                ('type_id', models.BigIntegerField(blank=True, null=True)),
                ('description_category_id', models.BigIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_autoarchived', models.BooleanField(default=False)),
                ('is_discounted', models.BooleanField(default=False)),
                ('is_kgt', models.BooleanField(default=False)),
                ('is_super', models.BooleanField(default=False)),
                ('is_seasonal', models.BooleanField(default=False)),
                ('is_prepayment_allowed', models.BooleanField(default=False)),
                ('primary_image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_type', models.CharField(choices=[('FBO', 'FBO'), ('FBS', 'FBS')], max_length=3)),
                ('sku', models.BigIntegerField()),
                ('date', models.DateTimeField()),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('warehouse_id', models.BigIntegerField(blank=True, null=True)),
                ('cluster_from', models.CharField(blank=True, max_length=255)),
                ('cluster_to', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('customer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tpl_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('posting_number', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.BigIntegerField()),
                ('warehouse_id', models.BigIntegerField()),
                ('warehouse_name', models.CharField(max_length=255)),
                ('available_stock_count', models.IntegerField(default=0)),
                ('return_from_customer_stock_count', models.IntegerField(default=0)),
                ('transit_stock_count', models.IntegerField(default=0)),
                ('stock_defect_stock_count', models.IntegerField(default=0)),
                ('cluster_id', models.BigIntegerField(blank=True, null=True)),
                ('cluster_name', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
