# Generated by Django 5.2.1 on 2025-05-24 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ozon', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbsstock',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbs_stocks', to='users.ozonstore'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.ozonstore'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='ozon.category'),
        ),
        migrations.AddField(
            model_name='sale',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='users.ozonstore'),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='ozon.product'),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wharehouse_stocks', to='users.ozonstore'),
        ),
        migrations.AlterUniqueTogether(
            name='fbsstock',
            unique_together={('store', 'sku', 'warehouse_id')},
        ),
        migrations.AlterUniqueTogether(
            name='warehousestock',
            unique_together={('store', 'sku', 'cluster_id', 'warehouse_id')},
        ),
    ]
