# Generated by Django 5.2.1 on 2025-05-27 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_cluster_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('average_delivery_time', models.FloatField()),
                ('impact_share', models.FloatField()),
                ('lost_profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recommended_supply', models.PositiveIntegerField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_clusters', to='users.ozonstore')),
            ],
            options={
                'verbose_name': 'Кластер доставки',
                'verbose_name_plural': 'Кластеры доставки',
                'unique_together': {('store', 'delivery_cluster_id')},
            },
        ),
    ]
