# Generated by Django 5.2.1 on 2025-05-27 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0003_deliverycluster'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryClusterItemAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.PositiveIntegerField()),
                ('cluster_name', models.CharField(max_length=100)),
                ('sku', models.BigIntegerField()),
                ('offer_id', models.CharField(max_length=100)),
                ('delivery_schema', models.CharField(max_length=10)),
                ('average_delivery_time', models.FloatField()),
                ('average_delivery_time_status', models.CharField(max_length=20)),
                ('impact_share', models.FloatField()),
                ('attention_level', models.CharField(max_length=20)),
                ('recommended_supply', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_item_analytics', to='users.ozonstore')),
            ],
            options={
                'unique_together': {('store', 'cluster_id', 'sku')},
            },
        ),
    ]
