# Generated by Django 5.2.1 on 2025-05-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0004_deliveryclusteritemanalytics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryclusteritemanalytics',
            options={'verbose_name': 'Аналитика по кластеру', 'verbose_name_plural': 'Аналитика по кластерам'},
        ),
        migrations.AlterField(
            model_name='sale',
            name='posting_number',
            field=models.CharField(max_length=255),
        ),
    ]
