# Generated by Django 5.2.1 on 2025-05-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0005_alter_deliveryclusteritemanalytics_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='posting_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
