# Generated by Django 5.2.1 on 2025-05-28 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0006_alter_sale_posting_number'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAnalyticsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_delivery_time', models.FloatField()),
                ('average_delivery_time_status', models.CharField(max_length=50)),
                ('total_orders', models.IntegerField()),
                ('lost_profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('impact_share', models.FloatField()),
                ('attention_level', models.CharField(max_length=50)),
                ('recommended_supply', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_summary', to='users.ozonstore')),
            ],
        ),
    ]
