# Generated by Django 5.2.1 on 2025-05-31 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0007_deliveryanalyticssummary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryanalyticssummary',
            options={'verbose_name': 'Сводную аналитику доставки', 'verbose_name_plural': 'Сводная аналитика доставки'},
        ),
    ]
