# Generated by Django 5.2.1 on 2025-08-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0008_alter_deliveryanalyticssummary_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryclusteritemanalytics',
            name='recommended_supply_FBO',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryclusteritemanalytics',
            name='recommended_supply_FBS',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
