# Generated by Django 5.2.1 on 2025-08-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0009_deliveryclusteritemanalytics_recommended_supply_fbo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehousestock',
            options={'verbose_name': 'Отатки на складах', 'verbose_name_plural': 'Отатки на складах'},
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='excess_stock_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='expiring_stock_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='other_stock_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='requested_stock_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='transit_defect_stock_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='valid_stock_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='waiting_docs_stock_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deliveryclusteritemanalytics',
            name='recommended_supply_FBO',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryclusteritemanalytics',
            name='recommended_supply_FBS',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
