# Generated by Django 5.2.1 on 2025-08-21 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0010_alter_warehousestock_options_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDailyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.BigIntegerField()),
                ('offer_id', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('date', models.DateField()),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ordered_units', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='users.ozonstore')),
            ],
            options={
                'verbose_name': 'Ежедневная аналитика товара',
                'verbose_name_plural': 'Ежедневная аналитика товаров',
                'unique_together': {('store', 'date', 'sku')},
            },
        ),
    ]
