# Generated by Django 5.2.5 on 2025-08-23 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0011_productdailyanalytics'),
        ('users', '0003_remove_ozonstore_performance_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('days', models.PositiveIntegerField(default=1)),
                ('promo_budget_pct', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('max_items', models.PositiveIntegerField(default=0)),
                ('price_min', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_max', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('train_days', models.PositiveIntegerField(default=0)),
                ('budget_mode', models.PositiveSmallIntegerField(default=0)),
                ('a_share', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('b_share', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('c_share', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('min_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('spreadsheet_url', models.URLField(blank=True, null=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('budget_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('selected_count', models.PositiveIntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_plan_requests', to='users.ozonstore')),
            ],
        ),
        migrations.CreateModel(
            name='AdPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.BigIntegerField()),
                ('offer_id', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('week_budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('day_budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('abc_label', models.CharField(blank=True, max_length=1)),
                ('ozon_campaign_id', models.CharField(blank=True, max_length=100)),
                ('campaign_name', models.CharField(blank=True, max_length=255)),
                ('campaign_type', models.CharField(blank=True, max_length=50)),
                ('adv_sales_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('adv_sales_units', models.IntegerField(blank=True, null=True)),
                ('adv_spend', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('adv_drr_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_sales_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_sales_units', models.IntegerField(blank=True, null=True)),
                ('tacos_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ozon.adplanrequest')),
            ],
            options={
                'verbose_name': 'Элемент рекламного плана',
                'verbose_name_plural': 'Элементы рекламного плана',
                'indexes': [models.Index(fields=['request', 'sku'], name='ozon_adplan_request_bc98da_idx')],
            },
        ),
    ]
