# Generated by Django 5.2.5 on 2025-08-23 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0012_adplanrequest_adplanitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adplanrequest',
            options={'verbose_name': 'Запрос на формирование рекламного плана', 'verbose_name_plural': 'Запросы на формирование рекламных планов'},
        ),
    ]
