# Generated by Django 5.2.5 on 2025-08-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0013_alter_adplanrequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdailyanalytics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
