# Generated by Django 5.2.5 on 2025-08-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0014_productdailyanalytics_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='adplanrequest',
            name='status',
            field=models.CharField(choices=[('preview', 'Предпросмотр'), ('activated', 'Активирован')], default='preview', max_length=20, verbose_name='Статус'),
        ),
    ]
