# Generated by Django 5.2.5 on 2025-08-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0015_adplanrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adplanitem',
            name='google_sheet_row',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер строки в Google таблице'),
        ),
    ]
