# Generated by Django 5.2.5 on 2025-08-31 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0016_adplanitem_google_sheet_row'),
        ('users', '0004_ozonstore_performance_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название кампании')),
                ('offer_id', models.CharField(blank=True, max_length=255, verbose_name='Offer ID')),
                ('sku', models.BigIntegerField(blank=True, null=True, verbose_name='SKU')),
                ('ozon_campaign_id', models.CharField(max_length=100, unique=True, verbose_name='ID кампании в Ozon')),
                ('week_budget', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Недельный бюджет')),
                ('daily_budget', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Дневной бюджет')),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Общий бюджет')),
                ('state', models.CharField(choices=[('CAMPAIGN_STATE_UNKNOWN', 'Неизвестно'), ('CAMPAIGN_STATE_ACTIVE', 'Активна'), ('CAMPAIGN_STATE_INACTIVE', 'Неактивна'), ('CAMPAIGN_STATE_PAUSED', 'Приостановлена'), ('CAMPAIGN_STATE_ENDED', 'Завершена')], default='CAMPAIGN_STATE_UNKNOWN', max_length=50, verbose_name='Статус кампании')),
                ('payment_type', models.CharField(choices=[('CPO', 'CPO'), ('CPC', 'CPC'), ('CPM', 'CPM')], default='CPO', max_length=10, verbose_name='Тип оплаты')),
                ('adv_object_type', models.CharField(choices=[('SKU', 'SKU'), ('CATEGORY', 'Категория')], default='SKU', max_length=20, verbose_name='Тип рекламного объекта')),
                ('from_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('placement', models.JSONField(blank=True, default=list, verbose_name='Места размещения')),
                ('product_autopilot_strategy', models.CharField(blank=True, max_length=100, verbose_name='Стратегия автопилота')),
                ('product_campaign_mode', models.CharField(blank=True, max_length=100, verbose_name='Режим кампании')),
                ('auto_increase_percent', models.PositiveIntegerField(default=0, verbose_name='Процент автоувеличения')),
                ('auto_increased_budget', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Автоувеличенный бюджет')),
                ('is_auto_increased', models.BooleanField(default=False, verbose_name='Автоувеличение включено')),
                ('recommended_auto_increase_percent', models.PositiveIntegerField(default=0, verbose_name='Рекомендуемый процент автоувеличения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual_campaigns', to='users.ozonstore')),
            ],
            options={
                'verbose_name': 'Ручная рекламная кампания',
                'verbose_name_plural': 'Ручные рекламные кампании',
                'indexes': [models.Index(fields=['ozon_campaign_id'], name='ozon_manual_ozon_ca_20875c_idx'), models.Index(fields=['sku'], name='ozon_manual_sku_a64221_idx'), models.Index(fields=['state'], name='ozon_manual_state_0ba5b8_idx'), models.Index(fields=['created_at'], name='ozon_manual_created_e338f9_idx')],
            },
        ),
    ]
