# Generated by Django 5.2.5 on 2025-09-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0017_manualcampaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualcampaign',
            name='state',
            field=models.CharField(choices=[('CAMPAIGN_STATE_UNKNOWN', 'Неизвестно'), ('CAMPAIGN_STATE_ACTIVE', 'Активна'), ('CAMPAIGN_STATE_INACTIVE', 'Неактивна'), ('CAMPAIGN_STATE_PAUSED', 'Приостановлена'), ('CAMPAIGN_STATE_ENDED', 'Завершена'), ('CAMPAIGN_STATE_RUNNING', 'Запущена'), ('CAMPAIGN_STATE_PLANNED', 'Запланирована'), ('CAMPAIGN_STATE_STOPPED', 'Остановлена (нехватка бюджета)'), ('CAMPAIGN_STATE_ARCHIVED', 'Архивная'), ('CAMPAIGN_STATE_MODERATION_DRAFT', 'Черновик модерации'), ('CAMPAIGN_STATE_MODERATION_IN_PROGRESS', 'На модерации'), ('CAMPAIGN_STATE_MODERATION_FAILED', 'Не прошла модерацию'), ('CAMPAIGN_STATE_FINISHED', 'Завершена (дата в прошлом)')], default='CAMPAIGN_STATE_UNKNOWN', max_length=50, verbose_name='Статус кампании'),
        ),
    ]
