# Generated by Django 5.2.5 on 2025-09-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0018_alter_manualcampaign_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualcampaign',
            name='ozon_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания в Ozon'),
        ),
        migrations.AddField(
            model_name='manualcampaign',
            name='ozon_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления в Ozon'),
        ),
    ]
