# Generated by Django 5.2.5 on 2025-09-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0019_manualcampaign_ozon_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adplanitem',
            name='has_existing_campaign',
            field=models.BooleanField(default=False, verbose_name='Есть реклама для SKU'),
        ),
    ]
