# Generated by Django 5.2.5 on 2025-09-02 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0020_adplanitem_has_existing_campaign'),
        ('users', '0004_ozonstore_performance_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adplanrequest',
            name='store',
        ),
        migrations.RemoveField(
            model_name='adplanitem',
            name='request',
        ),
        migrations.AlterModelOptions(
            name='adplanitem',
            options={'verbose_name': 'Рекламная кампания', 'verbose_name_plural': 'Рекламные кампании'},
        ),
        migrations.RemoveIndex(
            model_name='adplanitem',
            name='ozon_adplan_request_bc98da_idx',
        ),
        migrations.AddField(
            model_name='adplanitem',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ad_plan_items', to='users.ozonstore'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='adplanitem',
            index=models.Index(fields=['store', 'sku'], name='ozon_adplan_store_i_9a1012_idx'),
        ),
        migrations.AddIndex(
            model_name='adplanitem',
            index=models.Index(fields=['ozon_campaign_id'], name='ozon_adplan_ozon_ca_3b228f_idx'),
        ),
        migrations.DeleteModel(
            name='AdPlanRequest',
        ),
    ]
