# Generated by Django 5.2.5 on 2025-09-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0021_remove_adplanrequest_store_remove_adplanitem_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adplanitem',
            name='manual_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Ручной бюджет'),
        ),
    ]
