# Generated by Django 5.2.5 on 2025-09-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0022_adplanitem_manual_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='adplanitem',
            name='from_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AddField(
            model_name='adplanitem',
            name='ozon_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания в Ozon'),
        ),
        migrations.AddField(
            model_name='adplanitem',
            name='ozon_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления в Ozon'),
        ),
        migrations.AddField(
            model_name='adplanitem',
            name='payment_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='Тип оплаты'),
        ),
        migrations.AddField(
            model_name='adplanitem',
            name='placement',
            field=models.CharField(blank=True, max_length=50, verbose_name='Размещение'),
        ),
        migrations.AddField(
            model_name='adplanitem',
            name='product_autopilot_strategy',
            field=models.CharField(blank=True, max_length=50, verbose_name='Стратегия автопилота'),
        ),
        migrations.AddField(
            model_name='adplanitem',
            name='state',
            field=models.CharField(choices=[('CAMPAIGN_STATE_UNKNOWN', 'Неизвестно'), ('CAMPAIGN_STATE_ACTIVE', 'Активна'), ('CAMPAIGN_STATE_INACTIVE', 'Неактивна'), ('CAMPAIGN_STATE_PAUSED', 'Приостановлена'), ('CAMPAIGN_STATE_ENDED', 'Завершена'), ('CAMPAIGN_STATE_RUNNING', 'Запущена'), ('CAMPAIGN_STATE_PLANNED', 'Запланирована'), ('CAMPAIGN_STATE_STOPPED', 'Остановлена (нехватка бюджета)'), ('CAMPAIGN_STATE_ARCHIVED', 'Архивная'), ('CAMPAIGN_STATE_MODERATION_DRAFT', 'Черновик модерации'), ('CAMPAIGN_STATE_MODERATION_IN_PROGRESS', 'На модерации'), ('CAMPAIGN_STATE_MODERATION_FAILED', 'Не прошла модерацию'), ('CAMPAIGN_STATE_FINISHED', 'Завершена (дата в прошлом)')], default='CAMPAIGN_STATE_UNKNOWN', max_length=50, verbose_name='Статус кампании'),
        ),
        migrations.AddField(
            model_name='adplanitem',
            name='to_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='adplanitem',
            name='total_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Общий бюджет'),
        ),
    ]
