# Generated by Django 5.2.5 on 2025-09-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0023_adplanitem_from_date_adplanitem_ozon_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adplanitem',
            name='is_active_in_sheets',
            field=models.BooleanField(default=False, verbose_name='Активна в Google Sheets (колонка B)'),
        ),
    ]
