# Generated by Django 5.2.5 on 2025-09-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0024_adplanitem_is_active_in_sheets'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualcampaign',
            name='offer_id_list',
            field=models.JSONField(blank=True, default=list, verbose_name='Список всех Offer ID в кампании'),
        ),
        migrations.AddField(
            model_name='manualcampaign',
            name='sku_list',
            field=models.JSONField(blank=True, default=list, verbose_name='Список всех SKU в кампании'),
        ),
    ]
