# Generated by Django 5.2.5 on 2025-09-09 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0025_manualcampaign_offer_id_list_manualcampaign_sku_list'),
        ('users', '0004_ozonstore_performance_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adplanitem',
            name='train_days',
            field=models.PositiveIntegerField(default=5, verbose_name='Дней на обучение'),
        ),
        migrations.CreateModel(
            name='CampaignPerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ozon_campaign_id', models.CharField(help_text='ID кампании в Ozon (campaignId)', max_length=100)),
                ('report_uuid', models.CharField(max_length=64, unique=True)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Ожидается'), ('READY', 'Готов'), ('ERROR', 'Ошибка')], default='PENDING', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, help_text='Тело запроса на построение отчёта', null=True)),
                ('raw_response', models.JSONField(blank=True, help_text='Полный ответ отчёта как есть', null=True)),
                ('totals', models.JSONField(blank=True, help_text='Сводные метрики отчёта (report.totals)', null=True)),
                ('rows', models.JSONField(blank=True, help_text='Строки отчёта (report.rows)', null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to='users.ozonstore')),
            ],
            options={
                'verbose_name': 'Отчёт Performance API',
                'verbose_name_plural': 'Отчёты Performance API',
                'indexes': [models.Index(fields=['store', 'ozon_campaign_id'], name='ozon_campai_store_i_6c1a93_idx'), models.Index(fields=['report_uuid'], name='ozon_campai_report__2a02d0_idx'), models.Index(fields=['date_from', 'date_to'], name='ozon_campai_date_fr_ae0857_idx')],
                'unique_together': {('store', 'ozon_campaign_id', 'date_from', 'date_to')},
            },
        ),
    ]
