# Generated by Django 5.2.5 on 2025-09-10 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0026_adplanitem_train_days_campaignperformancereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignPerformanceReportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ozon_campaign_id', models.CharField(max_length=100)),
                ('totals', models.JSONField(blank=True, null=True)),
                ('rows', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ozon.campaignperformancereport')),
            ],
            options={
                'verbose_name': 'Кампания в отчёте Performance',
                'verbose_name_plural': 'Кампании в отчёте Performance',
                'indexes': [models.Index(fields=['ozon_campaign_id'], name='ozon_campai_ozon_ca_1e52d6_idx')],
                'unique_together': {('report', 'ozon_campaign_id')},
            },
        ),
    ]
