# Generated by Django 5.2.5 on 2025-09-13 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0027_campaignperformancereportentry'),
        ('users', '0004_ozonstore_performance_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAdControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_system_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ad_control', to='users.ozonstore')),
            ],
            options={
                'verbose_name': 'Управление рекламной системой магазина',
                'verbose_name_plural': 'Управление рекламной системой магазинов',
            },
        ),
    ]
