# Generated by hand

import django.db.models.deletion
from django.db import migrations, models


def populate_store_and_date(apps, schema_editor):
    Entry = apps.get_model('ozon', 'CampaignPerformanceReportEntry')

    for entry in Entry.objects.select_related('report').all():
        report = entry.report
        if report is None:
            continue
        entry.store_id = report.store_id
        entry.report_date = report.date_from.date()
        entry.save(update_fields=['store', 'report_date'])

    duplicates = []
    seen = {}
    for entry in Entry.objects.order_by('store_id', 'ozon_campaign_id', 'report_date', '-updated_at', '-id'):
        key = (entry.store_id, entry.ozon_campaign_id, entry.report_date)
        if any(v is None for v in key):
            continue
        if key in seen:
            duplicates.append(entry.pk)
        else:
            seen[key] = entry.pk

    if duplicates:
        Entry.objects.filter(pk__in=duplicates).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_ozonstore_performance_client_id_and_more'),
        ('ozon', '0028_storeadcontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignperformancereportentry',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_report_entries', to='users.ozonstore'),
        ),
        migrations.AddField(
            model_name='campaignperformancereportentry',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(populate_store_and_date, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='campaignperformancereportentry',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_report_entries', to='users.ozonstore'),
        ),
        migrations.AlterField(
            model_name='campaignperformancereportentry',
            name='report_date',
            field=models.DateField(),
        ),
        migrations.AddIndex(
            model_name='campaignperformancereportentry',
            index=models.Index(fields=['store', 'ozon_campaign_id', 'report_date'], name='ozon_campai_store_o_0d9311_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignperformancereportentry',
            constraint=models.UniqueConstraint(fields=['store', 'ozon_campaign_id', 'report_date'], name='ozon_report_entry_unique_store_campaign_date'),
        ),
    ]
