# Generated by Django 5.2.8 on 2025-11-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0031_adplanitem_is_mandatory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeadcontrol',
            options={'verbose_name': 'Вкл/Выкл', 'verbose_name_plural': 'Вкл/Выкл'},
        ),
        migrations.RenameIndex(
            model_name='campaignperformancereportentry',
            new_name='ozon_campai_store_i_9a0eb8_idx',
            old_name='ozon_campai_store_o_0d9311_idx',
        ),
    ]
