# Generated by Django 5.2.8 on 2025-11-21 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0032_alter_storeadcontrol_options_and_more'),
        ('users', '0008_storeexcludedproduct_storerequiredproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='OzonWarehouseDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_id', models.BigIntegerField()),
                ('warehouse_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('logistic_cluster_id', models.BigIntegerField()),
                ('logistic_cluster_name', models.CharField(max_length=255)),
                ('logistic_cluster_type', models.CharField(max_length=50)),
                ('macrolocal_cluster_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ozon_warehouses', to='users.ozonstore')),
            ],
            options={
                'verbose_name': 'Склад OZON',
                'verbose_name_plural': 'Справочник складов OZON',
                'indexes': [models.Index(fields=['store', 'warehouse_id'], name='ozon_ozonwa_store_i_726844_idx'), models.Index(fields=['logistic_cluster_id'], name='ozon_ozonwa_logisti_2e53e2_idx')],
                'unique_together': {('store', 'warehouse_id')},
            },
        ),
    ]
