# Generated by Django 5.2.8 on 2025-12-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0036_timeslot_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ozonsupplydraft',
            new_name='ozon_ozonsu_store_i_9c2924_idx',
            old_name='ozon_ozons_store_id_6006c7_idx',
        ),
        migrations.RenameIndex(
            model_name='ozonsupplydraft',
            new_name='ozon_ozonsu_operati_9eff25_idx',
            old_name='ozon_ozons_operati_44b308_idx',
        ),
        migrations.RenameIndex(
            model_name='ozonsupplydraft',
            new_name='ozon_ozonsu_batch_i_2d4174_idx',
            old_name='ozon_ozons_batch_i_b46082_idx',
        ),
    ]
