# Generated by Django 5.2.8 on 2025-12-18 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0037_operation_id_supply_created_status'),
        ('ozon', '0037_rename_ozon_ozons_store_id_6006c7_idx_ozon_ozonsu_store_i_9c2924_idx_and_more'),
    ]

    operations = [
    ]
