# Generated by Django 5.2.8 on 2025-12-18 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0038_merge_20251218_1857'),
        ('ozon', '0038_supply_order_fields'),
    ]

    operations = [
    ]
