# Generated by Django 5.2.8 on 2025-12-23 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0039_merge_20251218_2142'),
        ('ozon', '0039_supply_status_updated_at'),
    ]

    operations = [
    ]
