FROM python:3.11-slim

WORKDIR /workspace/backend
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
COPY backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY backend .
# RUN python manage.py collectstatic --noinput

CMD ["python", "-u", "manage.py", "runserver", "0.0.0.0:8000"]
# CMD ["gunicorn", "backend.wsgi:application", "--bind", "0.0.0.0:8000"]
