from django.urls import path
from .views import (
    SyncOzonProductView,
    SyncOzonCategoryTreeView,
    SyncOzonWarehouseStockView,
    SyncOzonSalesView,
    SyncFbsStockView,
    ProductAnalytics_V2_View,
    ProductAnalyticsByItemView,
    TriggerUpdateABCSheetView,
    CreateOrUpdateAdPlanView,
    TriggerSyncCampaignActivityOverrideView,
    ToggleStoreAdsStatusView,
    TriggerRebalanceAutoBudgetsView,
    UpdateWarehouseStockView,
    Planer_View,
    PlanerPivotView,
    OzonFboWarehouseSearchView,
    CreateSupplyDraftView,
    SupplyDraftBatchStatusView,
    SupplyDraftBatchListView,
    SupplyDraftBatchConfirmedListView,
    SupplyDraftSelectWarehouseView,
    SupplyDraftDeleteView,
    SupplyDraftTimeslotFetchView,
    SupplyDraftTimeslotListView,
    SupplyDraftCreateSupplyView,
    SupplyDraftSupplyStatusView,
)
urlpatterns = [
    path('ozon/products/', SyncOzonProductView.as_view()),
    path('ozon/categories/sync/', SyncOzonCategoryTreeView.as_view()),
    path('ozon/warehouse/sync/', SyncOzonWarehouseStockView.as_view()),
    path('ozon/sales/sync/', SyncOzonSalesView.as_view()),
    path('ozon/fbs-stock/sync/', SyncFbsStockView.as_view()),
    path("ozon/analytics/", ProductAnalytics_V2_View.as_view()),
    
    path("ozon/analytics/products/by-item/", ProductAnalyticsByItemView.as_view()),
    path("ozon/analytics/abc/update", TriggerUpdateABCSheetView.as_view()),
    path("ozon/createorupdateads/", CreateOrUpdateAdPlanView.as_view()),
    path("ozon/campaigns/sync-override/", TriggerSyncCampaignActivityOverrideView.as_view()),
    path("ozon/ads/toggle/", ToggleStoreAdsStatusView.as_view()),
    path("ozon/campaigns/rebalance-weekly/", TriggerRebalanceAutoBudgetsView.as_view()),
    path("ozon/warehouse/update/", UpdateWarehouseStockView.as_view()),
    path("ozon/planner/", Planer_View.as_view(), name="ozon-planner"),
    path("ozon/planner/pivot/", PlanerPivotView.as_view(), name="ozon-planner-pivot"),
    path("ozon/warehouse/fbo/search/", OzonFboWarehouseSearchView.as_view()),
    path("ozon/drafts/create/", CreateSupplyDraftView.as_view(), name="ozon-create-draft"),
    path("ozon/drafts/batch/<uuid:batch_id>/", SupplyDraftBatchStatusView.as_view(), name="ozon-draft-batch-status"),
    path("ozon/drafts/batches/", SupplyDraftBatchListView.as_view(), name="ozon-draft-batch-list"),
    path("ozon/drafts/batches/confirmed/", SupplyDraftBatchConfirmedListView.as_view(), name="ozon-draft-batch-confirmed-list"),
    path("ozon/drafts/<int:draft_id>/select-warehouse/", SupplyDraftSelectWarehouseView.as_view(), name="ozon-draft-select-warehouse"),
    path("ozon/drafts/<int:draft_id>/", SupplyDraftDeleteView.as_view(), name="ozon-draft-delete"),
    path("ozon/drafts/timeslots/fetch/", SupplyDraftTimeslotFetchView.as_view(), name="ozon-draft-timeslot-fetch"),
    path("ozon/drafts/batch/<uuid:batch_id>/timeslots/", SupplyDraftTimeslotListView.as_view(), name="ozon-draft-timeslot-list"),
    path("ozon/drafts/batch/<uuid:batch_id>/confirm-supply/", SupplyDraftCreateSupplyView.as_view(), name="ozon-draft-confirm-supply"),
    path("ozon/drafts/batch/<uuid:batch_id>/supply-info/", SupplyDraftSupplyStatusView.as_view(), name="ozon-draft-supply-info"),

]
