# Generated by Django 5.2.5 on 2025-08-23 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_ozonstore_performance_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ozonstore',
            name='performance_client_id',
        ),
        migrations.RemoveField(
            model_name='ozonstore',
            name='performance_client_secret',
        ),
        migrations.RemoveField(
            model_name='ozonstore',
            name='performance_service_account_number',
        ),
    ]
