# Generated by Django 5.2.5 on 2025-08-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_ozonstore_performance_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ozonstore',
            name='performance_client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ozonstore',
            name='performance_client_secret',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ozonstore',
            name='performance_service_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
