# Generated by Django 5.2.5 on 2025-02-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_ozonstore_performance_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ozonstore',
            name='google_sheet_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
