# Generated by Django 5.2.8 on 2025-11-10 07:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreFilterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planning_days', models.PositiveIntegerField(default=28)),
                ('analysis_period', models.PositiveIntegerField(default=28)),
                ('warehouse_weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6)),
                ('price_min', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=12)),
                ('price_max', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=12)),
                ('turnover_min', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6)),
                ('turnover_max', models.DecimalField(decimal_places=2, default=Decimal('90.00'), max_digits=6)),
                ('show_no_need', models.BooleanField(default=False)),
                ('sort_by', models.CharField(choices=[('orders', 'Orders'), ('revenue', 'Revenue'), ('ozon-rec', 'Ozon recommendations')], default='orders', max_length=32)),
                ('specific_weight_threshold', models.DecimalField(decimal_places=4, default=Decimal('0.0100'), max_digits=6)),
                ('turnover_from_stock', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filter_settings', to='users.ozonstore')),
            ],
            options={
                'verbose_name': 'Store filter setting',
                'verbose_name_plural': 'Store filter settings',
            },
        ),
    ]
